sudo: required
services:
  - docker

before_install:
  - docker build -t rakeshorange2018/docker-react -f Dockerfile.dev .

script:
  - docker run rakeshorange2018/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-application"
  env: "ReactApplication-env"
  bucket_name: "elasticbeanstalk-us-east-2-217012847344"
  bucket_path: "react-application"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
